/****************************************************************************
 *
 * Copyright (c) 2015 Ten Degrees, Inc. All rights reserved.
 *
 * This source is subject to the Ten Degrees Software License.
 * This software is protected by Copyright and the information and source code
 * contained herein is confidential. The software including the source code
 * may not be copied and the information contained herein may not be used or
 * disclosed except with the written permission of Ten Degrees, Inc.
 *
 * All other rights reserved.
 *
 * This code and information are provided "as is" without warranty of any
 * kind, either expressed or implied, including but not limited to the
 * implied warranties of merchantability and/or fitness for a
 * particular purpose.
 *
 *******************************************************************************
 * Revision information. DO NOT MODIFY. This is auto-generated by the SCM.
 *
 * $Id: ViewController.m 6349 2016-02-04 21:49:34Z jsolsma $
 *
 ****************************************************************************/

#import "ViewController.h"

@interface ViewController () <OnExtendUpdateDelegate, OnMapPressDelegate>

@property (weak, nonatomic) IBOutlet GMSMapView* mapView;


@end

@implementation ViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    [self setOnExtendUpdate:self];
    [self setOnMapPress:self];
    [self setAuthenticationKey:@"793e82a5c6bf11f43b65cc6ada893452"];
    [self setVicinityEnabled:true];
    [self setClarityEnabled:true];
    _mapView.accessibilityElementsHidden = NO;
    
    CLLocationCoordinate2D position = CLLocationCoordinate2DMake(41.659578, -91.535682);
    GMSMarker *marker = [GMSMarker markerWithPosition:position];
    marker.title = @"Seamen Center";
    marker.map = _mapView;
    
    CLLocationCoordinate2D position1 = CLLocationCoordinate2DMake(41.661922, -91.536895);
    GMSMarker *marker1 = [GMSMarker markerWithPosition:position1];
    marker1.title = @"MacBride Hall";
    marker1.map = _mapView;
    
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (void) onExtendReady:(bool)ready
{
    
}

- (void) onKeyValidation: (bool) validated
{
    if (validated)
    {
        [self start];
    }
}

-(void)onFacilityUpdateName:(NSString *)name onFacilityUpdateRegions:(NSArray *)regions onFacilityUpdateWaypoints:(NSArray *)waypoints onFacilityUpdateFloors:(NSArray *)floors onFacilityUpdateCategories:(NSArray *)categories
{
    
}

- (void) onRegionUpdateRegion: (Region *) region onRegionUpdateEntered: (bool) entered
{
    
}

- (void) onWaypointUpdateWaypoint: (Waypoint *) waypoint onWaypointUpdateArrived: (bool) arrived
{
    
}

- (void) onLongPressLatitude: (double) latitude onLongPressLongitude: (double) longitude onLongPressFloor: (int) floor
{
    
}

- (void) onPressLatitude: (double) latitude onPressLongitude: (double) longitude onPressFloor: (int) floor
{
    
}

- (void) onTouchElement: (NSString *) name
{
    
}

-(void)onMapStoppedMoving
{
    [self scaleUserDotTo: 20.0];
}

-(void)onLogOut
{

}

-(void)onFinalInvites:(NSArray *)invites
{

}

-(void)onNewInvites:(NSArray *)invites
{

}

-(void)onUnityMessages:(NSArray *)messages
{

}

-(void)onLocations:(NSDictionary *)locations
{

}

-(void)onGuidanceSet
{

}

-(void)onGuidanceDistanceChanged:(double)distance
{

}

-(void)onHighAccuracyPosition
{

}

-(void)onGuidanceEnd:(bool)arrived
{

}

-(void)onTouchElement:(NSString *)name withIconFilename:(NSString *)iconFilename withLat:(double)lat withLon:(double)lon andFloor:(int)floor withObject:(id)object
{
    
}

-(void)onUserMovedMap
{
    [self scaleUserDotTo: 19.0];
}

-(void)onMapChangedFloors:(NSString *)newFloorName withDirection:(int)direction
{

}

-(void)onPressedUserPositionIcon
{

}


@end
