/****************************************************************************
 *
 * Copyright (c) 2015 Ten Degrees, Inc. All rights reserved.
 *
 * This source is subject to the Ten Degrees Software License.
 * This software is protected by Copyright and the information and source code
 * contained herein is confidential. The software including the source code
 * may not be copied and the information contained herein may not be used or
 * disclosed except with the written permission of Ten Degrees, Inc.
 *
 * All other rights reserved.
 *
 * This code and information are provided "as is" without warranty of any
 * kind, either expressed or implied, including but not limited to the
 * implied warranties of merchantability and/or fitness for a
 * particular purpose.
 *
 *******************************************************************************
 * Revision information. DO NOT MODIFY. This is auto-generated by the SCM.
 *
 * $Id: ViewController.h 5264 2015-06-24 17:22:50Z pjohnson $
 *
 ****************************************************************************/
#import <UIKit/UIKit.h>
#import "GMapViewController.h"

@interface ViewController : GMapViewController

@property GMSPolyline * _Null_unspecified polyline;

@end

